import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
                <header className="border-b bg-background/60 backdrop-blur supports-[backdrop-filter]:bg-background/40">
                    <nav className="mx-auto max-w-6xl flex items-center gap-6 px-4 h-14 text-sm">
                        <Link href="/" className="font-semibold">QuizBuddy</Link>
                        <Link href="/quiz" className="hover:text-primary transition-colors">Quiz</Link>
                        <Link href="/study" className="hover:text-primary transition-colors">Q&A</Link>
                    </nav>
                </header>
                <main className="flex-1">{children}</main>
            </body>
        </html>
    );
}
